"""Server-side limits used by the material and recall APIs."""
MAX_UPLOAD_BYTES = 20 * 1024 * 1024
MAX_PDF_PAGES = 300
TXT_WORDS_PER_PAGE = 300
MATERIAL_TTL_SECONDS = 3 * 60 * 60
MAX_RANGE_PAGES = 60
MAX_CONTEXT_WORDS = 12_000
SAMPLED_EXCERPT_COUNT = 13
SUMMARY_MIN_WORDS = 15
SUMMARY_MAX_WORDS = 150
RATE_LIMIT_REQUESTS = 30
RATE_LIMIT_WINDOW_SECONDS = 60
MAX_FEEDBACK_SENTENCES = 2
MAX_MISSED_POINTS = 5
DEFAULT_GROQ_MODEL = "llama-3.3-70b-versatile"
